### ISSUE TITLE
Install EAP via SSH

### ISSUE THREAD

**Issue by joakimroeed** [AxisCommunications/acap3-examples#109]
How do we install our .eap files on to the camera via ssh? 
I've seen some reference eap-install.sh, but I don't know where to get a hold of that.

**Comment by pataxis** [comment]
If you work interactively with the [Dockerized ACAP SDK](https://hub.docker.com/r/axisecp/acap-sdk) which is available since 3.2 release you may run the SDK container and mount in your application directory which makes the source code available inside the SDK container, e.g.
`docker run -v $PWD/app:/opt/app --rm -i -t axisecp/acap-sdk:3.4-armv7hf-ubuntu20.04`
                                                                                
Now you have both build command `create-package.sh` and app management command `eap-install.sh` (which can install the .eap file) available on command line.
                       
More information on how to work interactively is found in the online documentation.
https://help.axis.com/acap-3-developer-guide#build-install-and-run-interactively-inside-container

**Other options:**
* Install via web GUI as is described in [ACAP 3 application examples](https://github.com/AxisCommunications/acap3-examples/tree/master/vdostream#install-your-application)
* Use the VAPIX APIs for applications https://www.axis.com/vapix-library/subjects/t10102231/section/t10036126/display
