### ISSUE TITLE
Storing stream  

### ISSUE THREAD

**Issue by joakimroeed** [AxisCommunications/acap3-examples#111]
I need some advice on how one can accomplish storing the stream from the camera on to a computer

**Comment by johan-bjareholt** [comment]
Assuming that you refer to saving a live stream to file, that is usually done with RTSP but other APIs such as streaming MJPEG over HTTP is also supported.
See the following page for documentation of the VAPIX Streaming API:
https://www.axis.com/vapix-library/subjects/t10037719/section/t10051110/display

Since our streaming APIs are based on open standards, there are lots of VMSes, programs and libraries that can save the stream to a file.
For example you could use VLC as follows:
1. Press "Media" button in toolbar
2. Press "Convert / Save" button
3. Press the "Network" tab
4. Enter "rtsp://CAMERA_IP/axis-media/media.amp" in the text field
5. Press "Convert / Save"
6. Select desired video/audio settings
7. Press "Start"
8. Press "Stop" once you want to stop the recording

You could also use libraries and frameworks such as GStreamer to stream video to a file using the following command if GStreamer and it's plugins are installed:
```
gst-launch-1.0 -e rtspsrc location="rtsp://root:pass@$IP/axis-media/media.amp?video=1&videocodec=h264" protocol=tcp ! rtph264depay ! h264parse ! mp4mux ! filesink location=recording.mp4
```

For changing stream settings, see the VAPIX documentation.
