### ISSUE TITLE
Audio processing example

### ISSUE THREAD

**Issue by rose-jinyang** [AxisCommunications/acap3-examples#176]
Hello
How are you?
Thanks for contributing to this project.
I am going to process audio through RTSP stream.
Where can I get a sample for audio processing  from RTSP stream?

**Comment by pataxis** [comment]
Hi @rose-jinyang ,

if you are looking for how to use audio APIs, the VAPIX library has a section for [Audio systems](http://vapix.tim-staging.se.axis.com/subjects/t10100065/section/t10100140/display) where I see `RTSP` streams are mentioned.

Since you opened an issue in this ACAP application example repository, I suspect you are looking for an example of `axaudio` which we don't have. But you have the [API documentation](https://help.axis.com/acap-3-developer-guide#version-history) and in the technical pages you find an example file [axaudioexample.c](https://www.axis.com/techsup/developer_doc/acap3/3.5/api/axaudio/html/axaudioexample_8c-example.html) that hopefully can give you some ideas on how to use this API.

A full example of `axaudio` with files `manifest.json`, `Makefile`, `LICENSE` etc. would be very similar to the structure of [vdostream](https://github.com/AxisCommunications/acap3-examples/tree/main/vdostream) example.

I could run a local example by

- Copy vdostream example
- Replace vdoencodeclient.c with axaudioexample.c
- Update names in manifest.json, something like
  ```json
  {
    "schemaVersion": "1.3",
    "acapPackageConf": {
        "setup": {
            "friendlyName": "audioApp",
            "appName": "audioApp",
            "vendor": "Axis Communications",
            "embeddedSdkVersion": "3.0",
            "user": {
                "group": "sdk",
                "username": "sdk"
            },
            "runMode": "never",
            "version": "1.0.0"
        }
     }
  }
  ```

- Update names in Makefile, something like
  ```Makefile
  PROGS     = audioApp
  
  PKGS = glib-2.0 gio-2.0 axaudio
  CFLAGS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --cflags $(PKGS))
  LDLIBS += $(shell PKG_CONFIG_PATH=$(PKG_CONFIG_PATH) pkg-config --libs $(PKGS))
  LDLIBS  += -lm
  CFLAGS   += -Wall -g -O2
  
  SRCS      = axaudioexample.c
  OBJS      = $(SRCS:.c=.o)
  
  all: $(PROGS)
  
  $(PROGS): $(OBJS)
  	$(CC) $(CFLAGS) $(LDFLAGS) $^ $(LDLIBS) -o $@
  
  clean:
  	rm -f $(PROGS) *.o pa* *.eap* *_LICENSE.txt

  ```
